#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Run PHPStan
if ! docker exec -i php /bin/bash -c "vendor/bin/phpstan analyse src"; then
    echo "PHPStan failed. Please fix the errors before committing."
    exit 1
fi

# Run PHP CS Fixer
if ! docker exec -i php /bin/bash -c "vendor/bin/php-cs-fixer fix src --rules=@PSR12"; then
	echo "PHP CS Fixer failed. Please fix the errors before committing."
	exit 1
fi	

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
